//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {

        [Required]
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("login")]
        public string login { get; set; }

        [Required]
        [DisplayName("Has³o")]
        [DataType(DataType.Password)]
        public string haslo { get; set; }
    }
}
