//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Admin
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Login")]
        public string login { get; set; }
        [DisplayName("Has³o")]
        public string haslo { get; set; }
    }
}
