//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.Wiadomosc = new HashSet<Wiadomosc>();
        }


        [Required]
        [DisplayName("ID")]
        public int id { get; set; } 

        [Required]
        [DisplayName("Og³oszenie ID")]
        public int ogloszenie_id { get; set; }

        [Required]
        [DisplayName("Zainteresowany ID")]
        public int zainteresowany_id { get; set; }

        [Required]
        [DisplayName("Og³aszaj¹cy ID")]
        public int oglaszajacy_id { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Ogloszenie Ogloszenie { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wiadomosc> Wiadomosc { get; set; }
    }
}
