//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Ocena
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("ID U¿ytkownika wystawiaj¹cego Ocenê")]
        public int ocena_od_id { get; set; }
        [DisplayName("ID U¿ytkownika otrzymuj¹cego Ocenê")]
        public int ocena_dla_id { get; set; }
        [DisplayName("Ocena")]
        public double ocena { get; set; }
        [DisplayName("Komentarz")]
        public string komentarz { get; set; }
    
        public virtual Uzytkownik OcenaDla { get; set; }
        public virtual Uzytkownik OcenaOd { get; set; }
    }
}
