//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ocena
    {

        [Required]
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("Od")]
        public int ocena_od_id { get; set; }

        [Required]
        [DisplayName("Dla")]
        public int ocena_dla_id { get; set; }

        [Required]
        [DisplayName("Ocena")]
        [Range(0, 5, ErrorMessage = "Ocena musi byæ w skali 0-5")]
        public double ocena1 { get; set; }

        public string komentarz { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }
}
