//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogloszenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogloszenie()
        {
            this.Chat = new HashSet<Chat>();
            this.Ulubiona = new HashSet<Ulubiona>();
            this.Zgloszenie = new HashSet<Zgloszenie>();
        }


        [Required]
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("Wystawi³ ID")]
        public int wystawil_id { get; set; }

        [Required]
        [DisplayName("Kategoria ID")]
        public int kategoria_id { get; set; }

        [Required]
        [DisplayName("Nazwa")]
        public string nazwa { get; set; }

        [Required]
        [DisplayName("Opis")]
        public string opis { get; set; }

        [DisplayName("Aktywne")]
        public bool aktywne { get; set; }

        [DisplayName("Dodano")]
        [DataType(DataType.DateTime)]
        public System.DateTime dodano { get; set; }

        [DisplayName("Typ")]
        public string typ { get; set; }

        [Required]
        [DisplayName("Cena")]
        [DataType(DataType.Currency)]
        public double cena { get; set; }

        [Required]
        [DisplayName("Do Negocjacji")]
        public bool negocjacja { get; set; }

        [Required]
        [DisplayName("Poka¿ Numer Telefonu")]
        public bool pokaz_tel { get; set; }

        [Required]
        [DisplayName("Poka¿ Adres Email")]
        public bool pokaz_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ulubiona> Ulubiona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgloszenie> Zgloszenie { get; set; }
    }
}
