//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Usunieci
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Imiê")]
        public string imie { get; set; }
        [DisplayName("Numer Telefonu")]
        public string nr_tel { get; set; }
        [DisplayName("Adres Email")]
        public string email { get; set; }
        [DisplayName("Has³o")]
        public string haslo { get; set; }
        [DisplayName("Do³¹czono")]
        public System.DateTime dolaczono { get; set; }
        [DisplayName("Usuniêto")]
        public System.DateTime usunieto { get; set; }
        [DisplayName("Zdjêcie")]
        public byte[] zdjecie { get; set; }
    }
}
