//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Wiadomosc
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("ID Chatu")]
        public int chat_id { get; set; }
        [DisplayName("ID Nadawcy")]
        public int nadawca_id { get; set; }
        [DisplayName("Wiadomoœæ")]
        public string wiadomosc { get; set; }
        [DisplayName("Wys³ano")]
        public System.DateTime wyslano { get; set; }
        [DisplayName("Przeczytano")]
        public bool przeczytano { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Uzytkownik Nadawca { get; set; }
    }
}
