//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Wiadomosc
    {

        [Required]
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("Chat ID")]
        public int chat_id { get; set; }

        [Required]
        [DisplayName("Nadawca ID")]
        public int nadawca_id { get; set; }

        [Required]
        [DisplayName("Treœæ")]
        public string wiadomosc1 { get; set; }

        [Required]
        [DisplayName("Wys³ano")]
        [DataType(DataType.DateTime)]
        public System.DateTime wyslano { get; set; }

        public bool przeczytano { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
