//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Zgloszenie
    {

        [Required]
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("Og³oszenie ID")]
        public int Ogloszenie_id { get; set; }

        [Required]
        [DisplayName("Zg³aszaj¹cy ID")]
        public int zglaszajacy_id { get; set; }

        [Required]
        [DisplayName("Zg³oszony ID")]
        public int zgloszony_id { get; set; }

        [Required]
        [DisplayName("Treœæ Zg³oszenia")]
        public string tresc { get; set; }
    
        public virtual Ogloszenie Ogloszenie { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }
}
