//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Zgloszenie
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("ID Og³oszenia")]
        public int ogloszenie_id { get; set; }
        [DisplayName("ID Zg³aszaj¹cego")]
        public int zglaszajacy_id { get; set; }
        [DisplayName("ID Zg³oszonego")]
        public int zgloszony_id { get; set; }
        [DisplayName("Treœæ Zg³oszenia")]
        public string tresc { get; set; }
    
        public virtual Ogloszenie Ogloszenie { get; set; }
        public virtual Uzytkownik Zglaszajacy { get; set; }
        public virtual Uzytkownik Zgloszony { get; set; }
    }
}
